[window]
opacity = 0.95
dimensions = { columns = 110, lines = 28 }

[font]
normal = { family = "Hack", style = "Regular" }

[shell]
program = "tmux"

[colors.primary]
background= '0x15161b'
foreground= '0xECECEC'

[colors.normal]
black=   '0x373b41'
red=     '0xa54242'
green=   '0x26BC39'
yellow=  '0xde935f'
blue=    '0x008cff'
magenta= '0x85678f'
cyan=    '0x5e8d87'
white=   '0x707880'

[colors.bright]
black=   '0x373b41'
red=     '0xcc6666'
green=   '0xb5bd68'
yellow=  '0xf0c674'
blue=    '0x81a2be'
magenta= '0xb294bb'
cyan=    '0x8abeb7'
white=   '0xc5c8c6'

[keyboard]
bindings = [
	{key = "Return", mods = "super" , action = "ToggleMaximized"},
	{key = "w", mods = "Control" , action = "None"},
	{key = "w", mods = "Control | Shift" , action = "None"},
]
